version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_chat_bot
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-password}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
      - N8N_METRICS=${N8N_METRICS:-false}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-false}
      - N8N_PERSONALIZATION_ENABLED=${N8N_PERSONALIZATION_ENABLED:-false}
      - N8N_VERSION_NOTIFICATIONS_ENABLED=${N8N_VERSION_NOTIFICATIONS_ENABLED:-false}
      - N8N_TEMPLATES_ENABLED=${N8N_TEMPLATES_ENABLED:-false}
      - N8N_ONBOARDING_FLOW_DISABLED=${N8N_ONBOARDING_FLOW_DISABLED:-true}
    volumes:
      # Mount your workflow folders
      - ./Apps:/home/node/.n8n/workflows/Apps
      - ./DataIntegration:/home/node/.n8n/workflows/DataIntegration
      - ./Training:/home/node/.n8n/workflows/Training
      # Mount n8n data directory for persistence
      - n8n_data:/home/node/.n8n
      # Optional: Mount credentials if you have them
      - ./credentials:/home/node/.n8n/credentials
    networks:
      - n8n_network

volumes:
  n8n_data:
    driver: local

networks:
  n8n_network:
    driver: bridge

